version: "3.8"
services:
  backend:
    build: .
    container_name: stage_back
    ports:
      - "5500:3000"
    environment:
      - MONGO_URI=mongodb://172.16.2.192:27017/db_stage

  db:
    image: mongo
    container_name: mongo_stage
    ports:
      - "27021:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
