version: "3.8"
services:
  backend:
    build: .
    ports:
      - "6600:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/db_prod

  db:
    image: mongo
    container_name: mongo_prod
    ports:
      - "27022:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
