version: "3.8"
services:
  backend:
    build: .
    container_name: dev_back
    ports:
      - "4400:3000"
    environment:
      - MONGO_URI=mongodb://mongo_dev:27020/db_dev
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo_dev
    ports:
      - "27020:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
