version: "3.8"
services:
  backend-prod:
    build: .
    container_name: prod_back
    ports:
      - "6600:3000"
    environment:
      - MONGO_URI=mongodb://172.16.2.192:27017/db_prod

volumes:
  db_data:
