version: "3.8"
services:
  backend:
    build: .
    container_name: dev_back
    ports:
      - "4400:3000"
    environment:
      - MONGO_URI=mongodb://172.16.2.192:27020/db_dev
    depends_on:
      - db
    networks:
      - dev_net

  db:
    image: mongo
    container_name: mongo_dev
    ports:
      - "27020:27017"
    volumes:
      - db_data:/data/db
    networks:
      - dev_net

networks:
  dev_net: # Define a docker network
    external: true

volumes:
  db_data: