version: "3.8"
services:
  backend:
    build: .
    container_name: dev_back
    ports:
      - "4400:3000"
    environment:
      - MONGO_URI=mongodb://172.16.2.192:27017/db_dev

  db:
    image: mongo
    container_name: mongo_dev
    ports:
      - "27020:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data: