name: Local Deploy

on:
  push:
    branches:
      - Dev
      - Stage
      - Prod

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}     

      - name: Local server Deployment
        run: |
          ssh -o StrictHostKeyChecking=no sadman-sajid@172.16.2.192 << 'EOF'
            cd /home/sadman-sajid/firstapp
            git fetch --all
            git checkout ${{ github.ref_name }}
            docker compose down
            docker compose up -d --build
          EOF
